version: 2

aliases:
  - &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:10-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore core dependencies cache
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Check that yarn.lock is not corrupted
          command: yarn repo-dirty-check
      - save_cache:
          name: Cache core dependencies
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - examples
            - packages

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build CRA preset
          command: yarn workspace @storybook/preset-create-react-app build
      - run:
          name: Build
          command: yarn workspaces run build

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  unit-test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - unit-test:
          requires:
            - install
